{pkgs, ...}: {
  home.packages = with pkgs; [
    eza
    starship
    zoxide
    ripgrep

    mise
  ];

  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;
    oh-my-zsh = {
      enable = true;
      plugins = [
        "git"
        "zsh-autosuggestions"
        "zsh-syntax-highlighting"
      ];
    };
    shellAliases = {
      l = "eza -lah --icons";
      ll = "eza -lah --icons";
      ls = "eza --icons";
    };
    history.size = 100000;
    # https://discourse.nixos.org/t/programs-neovim-defaulteditor-true-kills-bindkey-for-autosuggest-accept-in-zsh/48844
    defaultKeymap = "emacs";

    initContent = builtins.readFile ./.zshrc;
    # TODO: see the content in .zshrc generated by hm. split rc file so that its reusable with host OS
    # ~/.zshrc:source:21: no such file or directory: /oh-my-zsh.sh
    # ~/.zshrc:source:56: no such file or directory: ~/.oh-my-zsh/oh-my-zsh.sh
    # ~/.zshrc:source:69: no such file or directory: ~/.cargo/env
    # ~/.zshrc:73: no such file or directory: ~/.local/bin/mise
  };

  programs.starship = {
    enable = true;
    enableZshIntegration = true;
    settings = pkgs.lib.importTOML ./starship.toml;
  };

  programs.zoxide = {
    enable = true;
    enableZshIntegration = true;
  };

  programs.mise = {
    enable = true;
    enableZshIntegration = true;
    globalConfig = {
      tools = {
        node = "lts";
        python = "latest";
        uv = "latest";
      };
    };
  };
}
