set -g default-terminal "tmux-256color"
set -sa terminal-features ",*:RGB"
set -sa terminal-features ",*:usstyle"

set -g extended-keys on
set -g extended-keys-format csi-u

#setting the delay between prefix and command
set -s escape-time 5
set -g focus-events on

# Set bind key to reload configuration file
bind r \
	source-file ~/.config/tmux/tmux.conf \;\
	display 'Reloaded tmux config'

# Use | and - to split a window vertically and horizontally instead of " and % respectively
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
unbind %
bind - split-window -v -c "#{pane_current_path}"

# new-window in current working directory
bind c new-window -c "#{pane_current_path}"

# Bind D to resize the window to be 8 lines smaller
bind D resize-pane -D 8
bind U resize-pane -U 4

# Switch betwen panes using alt + arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Use shift + arrow key to move between windows in a session
bind -n S-Left  previous-window
bind -n S-Right next-window

set -g set-clipboard on
setw -g mode-keys vi

# Set the history limit so we get lots of scrollback.
setw -g history-limit 50000

# Refresh status line every 5 seconds - Good for when music is playing / update time etc
set -g status-interval 5

# Start window and pane indices at 1.
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# for image.nvim
set -gq allow-passthrough on
set -g visual-activity off
