tap "felixkratz/formulae"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
tap "sacloud/usacloud"
brew "age"
brew "lima"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-credential-helper"
brew "exiftool"
brew "git-crypt"
brew "git-delta"
brew "imagemagick"
brew "kind"
brew "kubernetes-cli"
brew "lua"
brew "luarocks"
brew "mas"
brew "mysql-client"
brew "pipx"
brew "qemu"
brew "ripgrep"
brew "stow"
brew "zoxide"
brew "knative-extensions/kn-plugins/func"
brew "knative-extensions/kn-plugins/quickstart"
brew "sacloud/usacloud/usacloud"
cask "1password"
cask "1password-cli"
cask "nikitabobko/tap/aerospace"
cask "discord"
cask "firefox@nightly"
cask "ghostty"
cask "gitify"
cask "google-chrome"
cask "karabiner-elements"
cask "keymapp"
cask "mos"
cask "notion"
cask "obsidian"
cask "raycast"
cask "spotify"
cask "vial"
cask "wezterm"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
cask "zed"
cask "zen"
mas "1Password for Safari", id: 1569813296
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
