{
  modulesPath,
  pkgs,
  lib,
  nixos-lima,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
    nixos-lima.nixosModules.lima
  ];

  networking.hostName = "lima-nixos";

  # Enable lima-init, lima-guestagent, other config needed for Lima support (via `nixos-lima.nixosModules.lima`)
  services.lima.enable = true;

  # ssh
  services.openssh.enable = true;

  nix.settings.experimental-features = ["nix-command" "flakes"];

  security = {
    sudo.wheelNeedsPassword = false;
  };

  # system mounts
  # These settings match the image file generated by the NixOS Lima VM image generator
  boot.loader.grub = {
    device = "nodev";
    efiSupport = true;
    efiInstallAsRemovable = true;
  };
  fileSystems."/boot" = {
    device = lib.mkForce "/dev/vda1"; # /dev/disk/by-label/ESP
    fsType = "vfat";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    autoResize = true;
    fsType = "ext4";
    options = ["noatime" "nodiratime" "discard"];
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;

  environment.systemPackages = with pkgs; [
    git
    zsh
    neovim
  ];

  system.stateVersion = "25.11";
}
